### ISSUE TITLE
Tar file datasets don't allow for "/"in key names for ASR training.

### ISSUE THREAD

**Issue by galv** [NVIDIA/NeMo#4455] opened 2022-06-27 21:26 UTC
**Is your feature request related to a problem? Please describe.**

Tar file datasets have two problems today that I am aware of:

1. The filenames inside tar files are *required* not to have "/" or "." in them. Disallowing "." is fine, given that it has special meaning in webdataset. Disallowing "/" causes some difficulties. First, if your key is larger than 255 elements and you convert "/" to "_" (as is done here https://github.com/NVIDIA/NeMo/blob/daf08760dde35433f934a5c38ab293bad3c22825/scripts/speech_recognition/convert_to_tarred_audio_dataset.py#L560, then it is not possible to untar the created tar file. You will get an error like this when running `untar`:

```
File name too long: 'gov_DOT_uscourts_DOT_illappct_DOT_1-07-3566-1-08-0702-1-08-0746-1-08-1373-1-08-1982-1-08-1983-1-08-2151-1-08-2152_gov_DOT_uscourts_DOT_illappct_DOT_1-07-3566-1-08-0702-1-08-0746-1-08-1373-1-08-1982-1-08-1983-1-08-2151-1-08-2152_DOT_2009-11-12_DOT_mp3_00000.flac'
```

This is because linux file names are at most 255 characters: https://serverfault.com/a/9548

2. Suppose that your tar dataset contains the following 4 entries:

```
speaker1/utterance1.wav
speaker1/utterance2.wav
speaker2/utterance1.wav
speaker2/utterance2.wav
```

Today, NeMo will convert the key `speaker1/utterance1.wav` into `${parent_dir_of_manifest}/speaker1/utterance1.wav`. That is to say that it believes that this makes. The code which does that is here:

https://github.com/NVIDIA/NeMo/blob/d8785e022e2ccaf8b02a27ca084aea5acd257b18/nemo/collections/common/parts/preprocessing/manifest.py#L92-L104

This code assumes that the keys of tar files have no "/" in them. A more straightforward way is to pass another argument "is_tar_dataset" into this function to accept tar files appropriately. I will show this below.

**Describe the solution you'd like**

I will link to a work-in-progress PR for "A more straightforward way is to pass another argument "is_tar_dataset" into this function to accept tar files appropriately." shortly after creating this issue. Edit: https://github.com/NVIDIA/NeMo/pull/4456

**Describe alternatives you've considered**

I wrote a quick workaround that converts "/" to "_" on the fly after loading the tar file and manifest here: https://github.com/NVIDIA/NeMo/compare/main...galv:tar-remove-slash-workaround

While you could make a "fix" by doing this conversion only when a tarred dataset is being used, this is rather clumsy since the ID changes. This makes debugging and downstream joins hard.

**Additional context**

Why should you make this change? NeMo tarred datasets can currently be created only by its convert_to_tarred_audio_dataset.py script, which cannot be parallelized via something like spark or some other big data processing framework. It is hard for users of big data technology to train on tarred datasets created directly via spark for this reason. Secondly, tar files are kind of the de facto standard by which speech training data is transferred today (see openslr.org, or https://huggingface.co/datasets/MLCommons/peoples_speech). It saves users time and money to be able to train directly on the tar files they have downloaded, instead of having to untar the download, and the retar it with changed names. The existing path basically increases the disk usage required from 2TiB (in the case of People's Speech) to 6TiB.

Additionally, if someone were training on a nemo tarred dataset created by convert_to_tarred_audio_dataset.py and didn't have the underlying data, they would not be able to untar most files simply to listen to them, as their keys will  most likely exceed 255 characters in length. This makes observability hard.

**Comment by titu1994** [comment] 2022-06-28 00:41
The reasoning for the problem and proposed solution is valid, but the approach is problematic. 

Tarred datasets use the flattened path in their dataloaders because the underlying assumption is that irrespective of what is the path of the tarfiles themselves, the contents are flattened and have no hierarchy at all. Your use case breaks that assumption. This assumption is necessary to simplify the data loader code for web datasets. 

For the tar dataset building script, we need to check that resultant audio filepath doesn't exceed this file length limitations. 

Now to discuss the auto resolution of relative paths - this is a recent change, which has unexpected issue with your use case. I don't believe the solution is to pass a boolean flag to multiple layers of code files, even if it works well. It invites future "edge case" solutions that will need even more flags. 

For your use case, you'd need a combination of 
1) update tarfiles creating script to have hierarchical structure
2) update multiple code files to resolve and then skip such hierarchical filepath with this new flag
3) optionally error out when building the tarfile dataset if it defects filepaths greater than 250 chars. 

Alternatively, we can revert this auto resolution of relative file path. 

I'm open to other solutions that don't require tracking down every implementation of parse_func

Fyi @stevehuang52 for the issue regarding relative path for manifests.

**Comment by galv** [comment] 2022-06-28 01:22
> For the tar dataset building script, we need to check that resultant audio filepath doesn't exceed this file length limitations.

This is not a particularly easy thing to do while avoiding collisions. Also, the output will have different keys from the input. This makes joining the output against a user's existing database difficult.

Today, simply trying to tar a data directory that is in a base directory that > 255 characters makes training on tar files impossible, according to this: https://github.com/NVIDIA/NeMo/blob/d8785e022e2ccaf8b02a27ca084aea5acd257b18/scripts/speech_recognition/convert_to_tarred_audio_dataset.py#L553. Users do not always have the ability to use a base directory that is shorter (consider working in a cgroup container, where you don't have control over your base directory; this is common in hadoop, kubernetes, spark jobs, etc.; or just working on a shared cluster where the legacy training system does not have such file length limitations).

Can you point to code where this concept of hierarchy comes in? Where is it beneficial? Why is it not also desired for tar files?

> Now to discuss the auto resolution of relative paths - this is a recent change, which has unexpected issue with your use case.

Okay, that makes sense. I didn't mention this in the first comment, but training on this dataset had worked a few months earlier. I had initially assumed there was a problem on my side rather than a change in NeMo. Thanks.

Also, an update: A colleague tried the workaround I linked to, but it results in `audio_file.is_file()` failing, when the key in a tar file is greater than 255 characters.

```
[NeMo W 2022-06-27 19:12:45 exp_manager:895] The checkpoint callback was told to monitor a validation value and trainer's max_steps was set to -1. Please ensure that max_steps will run for at least 1 epochs to ensure that checkpointing will not error out.
Created a temporary directory at /tmp/tmpkpdy71g9
Writing /tmp/tmpkpdy71g9/_remote_module_non_sriptable.py
Error executing job with overrides: ['n_gpus=1', 'model.train_ds.manifest_filepath=/data/the-peoples-speech/cc-by-clean/new_nemo_format_manifest.jsonl', 'model.validation_ds.manifest_filepath=/data/librispeech/dev_clean.json', 'exp_manager.exp_dir=/experiments']
Traceback (most recent call last):
  File "train_ctc_model.py", line 23, in main
    asr_model = EncDecCTCModel(cfg=cfg.model, trainer=trainer)
  File "/workspace/NeMo/nemo/collections/asr/models/ctc_models.py", line 50, in __init__
    super().__init__(cfg=cfg, trainer=trainer)
  File "/workspace/NeMo/nemo/core/classes/modelPT.py", line 138, in __init__
    self.setup_training_data(self._cfg.train_ds)
  File "/workspace/NeMo/nemo/collections/asr/models/ctc_models.py", line 349, in setup_training_data
    self._train_dl = self._setup_dataloader_from_config(config=train_data_config)
  File "/workspace/NeMo/nemo/collections/asr/models/ctc_models.py", line 298, in _setup_dataloader_from_config
    dataset = audio_to_text_dataset.get_tarred_dataset(
  File "/workspace/NeMo/nemo/collections/asr/data/audio_to_text_dataset.py", line 179, in get_tarred_dataset
    dataset = audio_to_text.TarredAudioToCharDataset(
  File "/workspace/NeMo/nemo/collections/asr/data/audio_to_text.py", line 885, in __init__
    super().__init__(
  File "/workspace/NeMo/nemo/collections/asr/data/audio_to_text.py", line 612, in __init__
    self.manifest_processor = ASRManifestProcessor(
  File "/workspace/NeMo/nemo/collections/asr/data/audio_to_text.py", line 127, in __init__
    self.collection = collections.ASRAudioText(
  File "/workspace/NeMo/nemo/collections/common/parts/preprocessing/collections.py", line 213, in __init__
    for item in manifest.item_iter(manifests_files):
  File "/workspace/NeMo/nemo/collections/common/parts/preprocessing/manifest.py", line 73, in item_iter
    item = parse_func(line, manifest_file)
  File "/workspace/NeMo/nemo/collections/common/parts/preprocessing/manifest.py", line 100, in __parse_item
    if not audio_file.is_file() and not audio_file.is_absolute() and audio_file.parent != Path("."):
  File "/opt/conda/lib/python3.8/pathlib.py", line 1439, in is_file
    return S_ISREG(self.stat().st_mode)
  File "/opt/conda/lib/python3.8/pathlib.py", line 1198, in stat
    return self._accessor.stat(self)
OSError: [Errno 36] File name too long: 'gov_DOT_uscourts_DOT_illappct_DOT_1-07-3566-1-08-0702-1-08-0746-1-08-1373-1-08-1982-1-08-1983-1-08-2151-1-08-2152_gov_DOT_uscourts_DOT_illappct_DOT_1-07-3566-1-08-0702-1-08-0746-1-08-1373-1-08-1982-1-08-1983-1-08-2151-1-08-2152_DOT_2009-11-12_DOT_mp3_00000.flac'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

So that won't work.

**Comment by titu1994** [comment] 2022-06-28 01:29
Hmm I think reverting this new change is overall better until a proper solution is in place. The PR has an issue, where it does a pass but still runs the next line of code which is the if check for audio filepath, replace with elif and try again. 

For the check inside the script, I meant error out if simply the len of the filepath was > 250 - no global check or deduplication etc. Ie don't let the user build an invalid tarfile with too long a filename. 

Tarfile dataloaders have no hierarchy. They can't since the number of files is determined by webdataset, and it simply counts the number of all files at the root of the opened tarfile. That's why there can be no directories inside of tarfiles for Webdataset. I dunno if they changed it in newer releases but we have so many Webdataset implementations now that breaking this assumption would break a lot of code.

**Comment by stevehuang52** [comment] 2022-06-28 02:06
Yes the current way to resolve relative paths is not optimal, since it assumes that filepaths for tarred datasets are all flattened as something like "_home_steve_datasets_wavs_xxxx.wav", which will cause problems when the filepath for a tarred datasets is a normal path with "/". I thought about adding a bool flag to solve this problem before, but it requires a lot of modifications on many function definitions, so I made a compromise. 

Well, if we do need to allow `./` and `/` in tarred datasets, the simplest way to avoid the problem is to revert adding support for resolving relative filepaths. However, personally I do think that supporting relative filepaths is very beneficial.

I have a question, why are we using the expanded filepath "_home_steve_datasets_wavs_xxxx.wav" but not the shorter one "wavs_xxxx.wav" when creating the tarred datasets? The shorter one can save some lengths for file names so it's less likely to exceed the length limitation.

**Comment by titu1994** [comment] 2022-06-28 05:21
In many datasets, filenames are repeated under different directories. Therefore only the absolute path is globally unique, not just the filename.

**Comment by galv** [comment] 2022-06-28 16:54
@stevehuang52 , with the understanding that you presumably don't want your change reverted, would something like this work for you as a workaround for what you desire?

 `sed "s/${partner_base_path}/${my_base_path}/g"   < partner_manifest.json > my_manifest.json`

I need to take some time to understand this limitation with webdataset:

> Tarfile dataloaders have no hierarchy. They can't since the number of files is determined by webdataset, and it simply counts the number of all files at the root of the opened tarfile. That's why there can be no directories inside of tarfiles for Webdataset. I dunno if they changed it in newer releases but we have so many Webdataset implementations now that breaking this assumption would break a lot of code.

I wasn't aware of it.

**Comment by stevehuang52** [comment] 2022-06-28 17:41
> @stevehuang52 , with the understanding that you presumably don't want your change reverted, would something like this work for you as a workaround for what you desire?
> 

Yes it will work, but that's tedious to do every time we move the whole dataset folder. Resolving relative file paths should be  automatically handled by the code itself, in my opinion.

I am fine with reverting the support for relative file paths, if it helps.

To my understanding, simply reverting the feature does not fully solves the problems. The filenames for audios can still be longer than 255 chars, which is still a problem regardless of whether we support relative filepaths. A possible solution might be to create new unique filenames for the audios when creating tarred datasets, and use a text file to record the ID mapping. For example, `/a/b/c/d/e/f/g/xxxxx.wav` can be renamed to `id-00000001-xxxxxxx.wav`, and we have a file  `mapping.txt` that looks like:
```
/a/b/c/d/e/f/g/xxxxx.wav, id-00001-xxxxxxx.wav
```
In this way, we solve both your problems, where we don't exceed the length limitation and is also able to recover the original file paths.

**Comment by titu1994** [comment] 2022-06-29 08:46
@galv in your pr, could you revert the support for relative data path entirely for now? We can come up with better solution in the future.

**Comment by stevehuang52** [comment] 2022-06-29 19:55
I think the following modification can support `/` in tarred dataset filenames
```
manifest_dir = Path(manifest_file).parent 
 audio_file = Path(item['audio_file']) 
 if not audio_file.is_file() and not audio_file.is_absolute() and audio_file.parent != Path("."): 
     # assume the wavs/ dir and manifest are under the same parent dir 
     audio_file = manifest_dir / audio_file 
     item['audio_file'] = str(audio_file.absolute()) 
     if not audio_file.is_file():  # handles tarred datasets
       item['audio_file'] = expanduser(item['audio_file']) 
 else: 
     item['audio_file'] = expanduser(item['audio_file']) 
```

**Comment by titu1994** [comment] 2022-07-03 18:00
The PR above fixes the issue regarding / in path, which should hopefully solve the issue of thread. Please try it out and see if it's sufficient. If not, reopen. 

For the long file name issue, a simple solution we can do is raise an explicit error if the length of the filename goes above 250 when building tarfiles and request use different directory structure or file name scheme. The other proposed alternatives cause breaking changes in ASR data loaders.

**Closed by titu1994** 2022-07-03 18:00 UTC
Labels: feature request
