### ISSUE TITLE
PunctCapitTokenClassifier checkpoints loading fails

### ISSUE THREAD

**Issue by m-zat** [NVIDIA/NeMo#829] opened 2020-07-08 13:06 UTC
Hello,

I am trying to follow the punctuation/capitalization tutorial.
Everything works except checkpoints for the class `PunctCapitTokenClassifier` are created according to a weird pattern:
```
punctcapittokenclassifier0-STEP-10-00.pt
```
This is okay except when I try to infer using in a Jupyter notebook.
The first time I infer something, checkpoints are loaded correctly. However the second time it fails because the neural factory looks for the checkpoint for the module `punctcapittokenclassifier1`.

I guess it is because in the infer routine function the module is recreated with a new integer appended. This is not the same behavior of other neural modules, such as JasperDecoder etc...

**Comment by ekmb** [comment] 2020-07-08 15:15
@m-zat after running training and then inference part multiple times, I couldn't reproduce your error with the latest master code. Could you share more details on how to reproduce, did you change anything in the notebook? Please also consider trying the inference script https://github.com/NVIDIA/NeMo/blob/master/examples/nlp/token_classification/punctuation_capitalization_infer.py

**Comment by m-zat** [comment] 2020-07-09 10:09
Thanks Evelina for having a look at the issue.

You are correct that the notebook works correctly however I still think there is something which is not 100% consistent to the other NeuralModules with respect to PunctCapitTokenClassifier.

For instance, when I train the BERT module in the same notebook I obtain some checkpoints with pattern
```BERT-STEP-1000.pt```
whereas with the above mentioned module I get the pattern
```punctcapittokenclassifier0-STEP-10-00.pt```
They look different not only for the letter casing but also for the fact that an integer is appended after the module name.

This has implications when I try to use a custom made `punctuation_capitalization_infer.py`.
To reproduce it one has to take the code from the script you linked and modify it in such a way to have only one function that basically wraps the whole script.
Now, the first time I call this function in a notebook the NeuralFactory tries to restore the checkpoints for module `punctcapittokenclassifier0`. However, the second time I run the function in the notebook, it fails to load the checkpoints as it tries to search them for the module `punctcapittokenclassifier1`.

Hope this is a bit clearer.

**Comment by ekmb** [comment] 2020-07-09 16:06
@m-zat could you please check if the issue persists after the PR is merged?

**Closed** 2020-07-09 16:32 UTC
