### ISSUE TITLE
get_samples wrong dtype

### ISSUE THREAD

**Issue by roman-vygon** [NVIDIA/NeMo#3982] opened 2022-04-13 06:07 UTC
**Describe the bug**

nemo.collections.asr.parts.utils.decoder_timestamps_utils.get_samples fails if the audio file's original sample rate differs from the target sample rate.

`ParameterError: Audio data must be floating-point`

**Steps/Code to reproduce bug**

```python
from pydub import AudioSegment
from nemo.collections.asr.parts.utils.decoder_timestamps_utils import get_samples

segment = AudioSegment.silent(duration=1000).set_frame_rate(22050)
segment.export('test.wav', format='wav')
get_samples('test.wav')
```
**Expected behavior**

File is resampled successfully.

**Environment overview (please complete the following information)**

 - Method of NeMo install: pip
 - NeMo version: 1.6.2
 - librosa version: 0.8.1

**Comment by nithinraok** [comment] 2022-05-09 17:13
@tango4j that snippet code creates a wav file at 22500 Khz and the user tries to use `get_samples` code to get samples at target sr (16000). 

I think you can use librosa.load(audio_file,target_sr) to resample if orginal sample rate doesn;t match with target_sr

**Comment by okuchaiev** [comment] 2022-06-03 17:45
@tango4j and/or @nithinraok  is this issue resolved or is it a non-issue? Please close if resolved

**Comment by tango4j** [comment] 2022-06-03 20:13
As @nithinraok mentioned, Instead of using pydub, use `data, sr = librosa.load(audio_file_path, sr=TARGET_SR)` by specifying TARGET_SR= 22050. This has been successfully working with NeMo Feature extractor. Since this is not a bug from `get_samples` function in NeMo, I will close this.

**Comment by nithinraok** [comment] 2022-06-07 20:59
I would suggest seeing what's happening with the error here. 
and may be a better way is to use `data, sr = librosa.load(audio_file_path, sr=TARGET_SR)` instead of read and resample. 
https://github.com/NVIDIA/NeMo/blob/d4246c59f47894aa8e04cea6485775edc4ed6574/nemo/collections/asr/parts/utils/decoder_timestamps_utils.py#L224

**Closed** 2022-07-03 18:08 UTC
Labels: bug
