### ISSUE TITLE
Running NeMo on Linux or Collab and not working

### ISSUE THREAD

**Issue by antandrieux** [NVIDIA/NeMo#1867] opened 2021-03-09 00:05 UTC
Hello everyone,

I have some problems trying NeMo. I want to setup an environment on a Linux machine but after the installation of nemo_toolkit, the import (_import nemo.collections.nlp as nemo_nlp_) keeps rejecting an error: 
**ImportError: cannot import name 'Batch' from 'torchtext.data' (/usr/local/lib/python3.7/dist-packages/torchtext/data/__init__.py)
**

I also tried the projects from a NeMo example (https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/nlp/Punctuation_and_Capitalization.ipynb) but I got the same issue...

Can anyone tell me if I miss something? Thank you all in advance!

Yours.

**Comment by titu1994** [comment] 2021-03-09 00:11
This is a pytorch lightning issue, please downgrade to 1.2.1 for the time being until they are able to support pytorch 1.8 as well as it's dependency of torchtext

**Comment by antandrieux** [comment] 2021-03-09 10:41
> This is a pytorch lightning issue, please downgrade to 1.2.1 for the time being until they are able to support pytorch 1.8 as well as it's dependency of torchtext

Me neither :/

**Comment by tiborkiss** [comment] 2021-03-09 21:49
I described already here https://github.com/NVIDIA/NeMo/issues/1868

**Comment by ericharper** [comment] 2021-04-20 05:33
Duplicate of #1868

**Closed by ericharper** 2021-04-20 05:33 UTC
