### ISSUE TITLE
[Question] ASR Correction 

### ISSUE THREAD

**Issue by amejri** [NVIDIA/NeMo#1246] opened 2020-10-01 10:27 UTC
Hi guys,
Can someone tell me how to apply a postprocessing for the english pretrained model ?
Thanks in advance.

**Comment by okuchaiev** [comment] 2020-10-02 05:09
closing as duplicate of https://github.com/NVIDIA/NeMo/issues/1220 we are working on it

**Closed by okuchaiev** 2020-10-02 05:09 UTC
Labels: question
