### ISSUE TITLE
Problems with MTEncDecModel model in ONNX

### ISSUE THREAD

**Issue by Vlados09** [NVIDIA/NeMo#3434] opened 2022-01-13 16:20 UTC
There are two issues I am having with exporting [MTEncDecModel](https://github.com/NVIDIA/NeMo/blob/r1.2.0/nemo/collections/nlp/models/machine_translation/mt_enc_dec_model.py) to ONNX, they might be related in some way so going to post them together.

## 1. ONNX error in embedding in nemo version > 1.2:

If I try to run below example in nemo 1.5 I get the following error:

```
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : 
Non-zero status code returned while running Reshape node. Name:'Reshape_67' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/tensor/reshape_helper.h:41
onnxruntime::ReshapeHelper::ReshapeHelper(const onnxruntime::TensorShape&, std::vector<long int>&, bool)
gsl::narrow_cast<int64_t>(input_shape.Size()) == size was false. 
The input tensor cannot be reshaped to the requested shape. Input shape:{1,44,1024}, requested shape:{2,16,16,64}
```
However, it seems like this error is not present if using an older version of nemo.

## 2. Big performance discrepancy when using ONNX version of the model:
I notice a big performance drop when exporting the MTEncDecModel to ONNX. I am trying a minimal setup with greedy search and get about half the BLEU score in comparison to using MTEncDecModel directly with `TopKSequenceGenerator(top_k=1)`.

Here is a full script to get the translation with ONNX, you would need to additionally install  `onnxruntime-gpu`:
```python
import torch
import numpy as np
import onnxruntime
from nemo.collections.nlp.models import MTEncDecModel

# Load the model form pretrained:
model = MTEncDecModel.from_pretrained('nmt_en_de_transformer12x2')

# Export all model components to onnx:
model.encoder.export('encoder.onnx')
model.decoder.export('decoder.onnx')
model.log_softmax.export('classifier.onnx')

# Initialise all the onnx sessions:
encoder_session = onnxruntime.InferenceSession('encoder.onnx', providers=['CUDAExecutionProvider'])
decoder_session = onnxruntime.InferenceSession('decoder.onnx', providers=['CUDAExecutionProvider'])
classifier_session = onnxruntime.InferenceSession('classifier.onnx', providers=['CUDAExecutionProvider'])

# Preprocess the data using the original nemo model for simplicity:
TEXT = ['They are not even 100 metres apart: On Tuesday, the new B 33 pedestrian lights in Dorfparkplatz in Gutach became operational - within view of the existing Town Hall traffic lights.']
src_ids, src_mask = model.prepare_inference_batch(TEXT)
src_ids = src_ids.cpu().numpy()  # Convert to numpy for use with onnx
src_mask = src_mask.cpu().numpy().astype(int)

# Compute encoder hidden state:
encoder_input = {'input_ids': src_ids, 'encoder_mask': src_mask}
encoder_hidden_state = encoder_session.run(['last_hidden_states'], encoder_input)[0]

# Simple greedy search:
MAX_GENERATION_DELTA = 5
BOS = model.encoder_tokenizer.bos_id
EOS = model.encoder_tokenizer.eos_id
PAD = model.encoder_tokenizer.pad_id

def decode(tgt: np.array, embeding: np.array, src_mask: np.array) -> np.array:
      decoder_input = {
          'input_ids': tgt,
          'decoder_mask': (tgt != PAD).astype(np.int64),
          'encoder_mask': embeding,
          'encoder_embeddings': src_mask
      }
      decoder_hidden_state = decoder_session.run(['last_hidden_states'], decoder_input)[0]
      log_probs = classifier_session.run(['log_probs'], {'hidden_states': decoder_hidden_state})[0]
      return log_probs

max_out_len = encoder_hidden_state.shape[1] + MAX_GENERATION_DELTA
tgt=np.full(shape=encoder_hidden_state.shape[:-1], fill_value=0)
tgt[:, 0] = BOS

for i in range(1, max_out_len):
    log_probs = decode(tgt[:, :i], encoder_hidden_state, src_mask)
    next_tokens = log_probs[:, -1].argmax(axis=1) # NOTE: ONNX decoder returns multiple outputs which is different to pytorch version, so I get the last one (this could be where error is?)
    tgt[:, i] = next_tokens
    if ((tgt == EOS).sum(axis=1) > 0).all():
        break

tgt_torch = torch.from_numpy(tgt).to('cuda:0')
onnx_translation = model.ids_to_postprocessed_text(tgt_torch, model.decoder_tokenizer, model.target_processor)
```

I have run above against newstest2014 set and got a BLUE score of 13 vs 29 if I use `MTEncDecModel.translate` method. It seems like onnx model works well for shorter sentences, but for the longer ones it cuts off too soon. Could be because torch model uses decoder_mems, and onnx doesn't? 

Is there maybe a better way to set up onnx inference? 

**Environment overview (please complete the following information)**
- Environment Location: Docker on Kubernetes
- Method of NeMo install: using helm chart using nvcr.io/nvidia/nemo:1.2.0 / 1.5.1
- Additionally install `pip install onnxruntime-gpu==1.10.0`

**Comment by aklife97** [comment] 2022-01-20 07:05
@Vlados09, as you recognized, the issue is with the input/output you're providing to the decoder. 

the decoder ONNX model expects the input: 
`decoder_input=[input_ids, decoder_mask, encoder_mask, encoder_embeddings, decoder_mems])`

In your code, you don't seem to be passing decoder_mems. 
Decoder_mems are a concatenation of outputs of each attention block from the previous decode iteration. We cache and return these mems as they help speed up the subsequent decode iteration.

So, to work with this, you'd need to do the following:

```
decoder_hidden_state = decoder_session.run(['last_hidden_states'], decoder_input)[0] # Output Shape: [batch_size, num_decoder_attention_layers+2, seqlen, embedding_dim]
log_probs = classifier_session.run(['log_probs'], {'hidden_states': decoder_hidden_state[:,-1,-1:]})[0]
return log_probs, decoder_hidden_state
```

additionally while calling decode, you'd have to provide the previous hidden_state as input:
`log_probs, decoder_hidden_state = decode(tgt[:, :i], encoder_hidden_state, src_mask, decoder_hidden_state)`


Another thing to note is that during the first decode iteration, you'd need to provide a "blank" input to the decoder_hidden_state. To do this, you can initialize the decoder_hidden_state as:
`decoder_hidden_state = np.ones((bsize, num_decoder_attention_layers+2, 0, embedding_dim)).astype("float32")`

**Comment by Vlados09** [comment] 2022-01-24 11:29
@aklife97 on the older version of nemo (1.2) the decoder does not have `decoder_mems` as an input version, here is the full io from the onnx session:
```
Inputs: 
input_ids : ['input_ids_dynamic_axes_1', 'input_ids_dynamic_axes_2']
decoder_mask : ['decoder_mask_dynamic_axes_1', 'decoder_mask_dynamic_axes_2']
encoder_mask : ['encoder_mask_dynamic_axes_1', 'encoder_mask_dynamic_axes_2', 1024]
encoder_embeddings : ['encoder_embeddings_dynamic_axes_1', 'encoder_embeddings_dynamic_axes_2']

Outputs: 
last_hidden_states: ['last_hidden_states_dynamic_axes_1', 'last_hidden_states_dynamic_axes_2', 1024]
```

Looks like latest version does have `decoders_mems_list` as an input, however, the error I get on the newer version is within the `encoder` in this line:
```python
encoder_hidden_state = encoder_session.run(['last_hidden_states'], encoder_input)[0]
```
Its same error as I mentioned above.

**Comment by aklife97** [comment] 2022-01-29 00:51
Oh I see, @Vlados09 the issue you're facing is probably linked to a known ONNX export issue with PyTorch.  
We recently pushed a workaround to handle it in #3422 
Would it be possible for you to install NeMo from source using the main branch? This should most likely fix the error

**Comment by aklife97** [comment] 2022-02-08 23:17
Update: NeMo versions >=1.6.0 include the ONNX export workaround

**Comment by Vlados09** [comment] 2022-02-16 13:01
Thank for the update @aklife97, do you know when 1.6 image will be uploaded to ngc?

**Comment by aklife97** [comment] 2022-02-16 18:43
There's been some delay with container releases lately, but as a solution, you can go ahead and build your own container using the Dockerfile. More details on it here: https://github.com/NVIDIA/NeMo/discussions/3689

**Comment by Vlados09** [comment] 2022-03-11 12:44
Hi again,

So the issue with the encoder has been resolved. I am now not sure what to input into the ONNX model for the decoder mems list as the first input? If I set it to None similar to how its called in pure pytorch I get the following error:

```
[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Transpose node. Name:'Transpose_15' Status Message: /onnxruntime_src/include/onnxruntime/core/framework/op_kernel_context.h:40 const T* onnxruntime::OpKernelContext::Input(int) const [with T = onnxruntime::Tensor] Missing Input: decoder_mems
```

I am guessing it expects a fixed size array, what can I fill the array with to make it work as expected?

**Comment by aklife97** [comment] 2022-03-22 23:00
Hey @Vlados09, quoting above:

> Another thing to note is that during the first decode iteration, you'd need to provide a "blank" input to the decoder_hidden_state. To do this, you can initialize the decoder_hidden_state as:
> decoder_hidden_state = np.ones((bsize, num_decoder_attention_layers+2, 0, embedding_dim)).astype("float32")
> 

Let me know if this resolves the issue.

**Comment by okuchaiev** [comment] 2022-04-05 23:51
Closing. Please open a new issue is there are other problems or re-open this one if this exact issue persists in 1.7.2 or above.

**Closed by okuchaiev** 2022-04-05 23:51 UTC
Labels: bug

**Comment by savinay** [comment] 2022-07-13 22:11
What is the value of bsize, num_decoder_attention_layers, seqlen, embedding_dim for the first decode iteration?
