### ISSUE TITLE
index out of dimension in sd_model.diarize() "Speaker_Diarization_Inference"

### ISSUE THREAD

**Issue by CaioRochaGoes** [NVIDIA/NeMo#3137] opened 2021-11-04 14:03 UTC
**Describe the bug**

I'm using "Speaker Diarization Inference" but 'vad_marblenet' wasn't enough, I decided to do the Fine-tune training on the vad model as in the example of "Speech_Commands.ipynb" which is mentioned at the end of the Voice_Activity_Detection notebook.
After the model's Fine-tune I tested it, and the following error came back

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_704/3722763614.py in <module>
----> 1 sd_model.diarize()

/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/models/clustering_diarizer.py in diarize(self, paths2audio_files, batch_size)
    352 
    353             self._setup_vad_test_data(manifest_vad_input)
--> 354             self._run_vad(manifest_vad_input)
    355         else:
    356             if not os.path.exists(self._speaker_manifest_path):

/opt/conda/lib/python3.8/site-packages/nemo/collections/asr/models/clustering_diarizer.py in _run_vad(self, manifest_file)
    201                 log_probs = self._vad_model(input_signal=test_batch[0], input_signal_length=test_batch[1])
    202                 probs = torch.softmax(log_probs, dim=-1)
--> 203                 pred = probs[:, 1]
    204                 if status[i] == 'start':
    205                     to_save = pred[:-trunc]

IndexError: index 1 is out of bounds for dimension 1 with size 1
```

**Steps/Code to reproduce bug**

```
pretrained_vad = 'vad_marblenet_Fine_Tune.nemo'
pretrained_speaker_model = 'ecapa_tdnn'
```
default config.diarizer cell values

**Expected behavior**

Execution of VAD and embendding calculations

**Environment overview (please complete the following information)**

 - Environment location: [Docker]

**Environment details**

NVIDIA docker image.

**Comment by titu1994** [comment] 2021-11-30 23:11
@fayejf @nithinraok

**Comment by okuchaiev** [comment] 2022-04-05 23:42
Closing. @CaioRochaGoes please re-open if the issue is still relevant.

**Closed by okuchaiev** 2022-04-05 23:42 UTC
Labels: bug
