### ISSUE TITLE
Diarization Inference Parameters

### ISSUE THREAD

**Issue by CaioRochaGoes** [NVIDIA/NeMo#3247] opened 2021-11-25 13:30 UTC
Hey guys,

I'm using "Speaker_Diarization_Inference.ipynb", I'm having a problem with Vad Diarization parameters
```
output_dir = os.path.join(ROOT,'outputs')
config.diarizer.paths2audio_files = paths2audio_files
config.diarizer.path2groundtruth_rttm_files = path2groundtruth_rttm_files
config.diarizer.out_dir = output_dir # Directory to store intermediate files and prediction outputs
config.diarizer.speaker_embeddings.model_path = pretrained_speaker_model

#Here we use our inhouse pretrained NeMo VAD 
config.diarizer.vad.model_path = pretrained_vad
config.diarizer.vad.window_length_in_sec = 0.15
config.diarizer.vad.shift_length_in_sec = 0.01
# config.diarizer.vad.threshold = 0.8 threshold would be deprecated in release 1.5
config.diarizer.vad.postprocessing_params.onset = 0.8 
config.diarizer.vad.postprocessing_params.offset = 0.7
config.diarizer.vad.postprocessing_params.min_duration_on = 0.1
config.diarizer.vad.postprocessing_params.min_duration_off = 0.3
```
Testing with different audios, I have to constantly change the parameters to get a better result with each audio, or avoid the error
`IndexError: list index out of range`

This happens to me mainly in version 1.4.0 of Nemo, in version 1.5.0 I noticed an improvement but still occurs the cases.

I'm not using the "vad_marblenet" model because it wasn't meeting my needs, I'm using a model that I'm training with "Voice_Activity_Detection.ipynb"

My question is if there is any metric for setting the values ​​of these parameters?
If you have an ideal value for these parameters, which has better results with a greater number of audios that go through the script?

**Comment by nithinraok** [comment] 2021-11-30 23:25
If you have reference VAD labels, You could use this [script](https://github.com/NVIDIA/NeMo/blob/main/scripts/voice_activity_detection/vad_tune_threshold.py) to find onset and offset parameters (threshold), you could fix vad window length and shift length as provided in config. Min duration on and off are the parameters to configure for smooth output labels, so keeping them as shown in config or tweaking by +-0.1 sec should be good too.

**Comment by CaioRochaGoes** [comment] 2021-12-02 20:27
I'm trying to use the script you recommended, but I don't think I'm doing it right.
Example, the output it generates for me is this: 
```
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

[NeMo I 2021-12-02 20:05:58 vad_utils:619] parameter {'offset': 0.0, 'onset': 0.0}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:58 vad_utils:619] parameter {'offset': 0.0, 'onset': 0.2}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:59 vad_utils:619] parameter {'offset': 0.0, 'onset': 0.4}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:59 vad_utils:619] parameter {'offset': 0.0, 'onset': 0.6000000000000001}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:59 vad_utils:619] parameter {'offset': 0.0, 'onset': 0.8}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:59 vad_utils:619] parameter {'offset': 0.2, 'onset': 0.0}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:59 vad_utils:619] parameter {'offset': 0.2, 'onset': 0.2}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:59 vad_utils:619] parameter {'offset': 0.2, 'onset': 0.4}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:59 vad_utils:619] parameter {'offset': 0.2, 'onset': 0.6000000000000001}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:59 vad_utils:619] parameter {'offset': 0.2, 'onset': 0.8}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:05:59 vad_utils:619] parameter {'offset': 0.4, 'onset': 0.0}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:00 vad_utils:619] parameter {'offset': 0.4, 'onset': 0.2}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:00 vad_utils:619] parameter {'offset': 0.4, 'onset': 0.4}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:00 vad_utils:619] parameter {'offset': 0.4, 'onset': 0.6000000000000001}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:00 vad_utils:619] parameter {'offset': 0.4, 'onset': 0.8}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:00 vad_utils:619] parameter {'offset': 0.6000000000000001, 'onset': 0.0}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:00 vad_utils:619] parameter {'offset': 0.6000000000000001, 'onset': 0.2}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:00 vad_utils:619] parameter {'offset': 0.6000000000000001, 'onset': 0.4}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:00 vad_utils:619] parameter {'offset': 0.6000000000000001, 'onset': 0.6000000000000001}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:01 vad_utils:619] parameter {'offset': 0.6000000000000001, 'onset': 0.8}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:01 vad_utils:619] parameter {'offset': 0.8, 'onset': 0.0}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:01 vad_utils:619] parameter {'offset': 0.8, 'onset': 0.2}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:01 vad_utils:619] parameter {'offset': 0.8, 'onset': 0.4}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:01 vad_utils:619] parameter {'offset': 0.8, 'onset': 0.6000000000000001}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:01 vad_utils:619] parameter {'offset': 0.8, 'onset': 0.8}, {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
[NeMo I 2021-12-02 20:06:01 vad_tune_threshold:128] Best combination of thresholds for binarization selected from input ranges is {'offset': 0.0, 'onset': 0.0}, and the optimal score is {'DetER (%)': 0.0, 'FA (%)': nan, 'MISS (%)': nan}
```
He tells me that the best combination would be {'offset': 0.0, 'onset': 0.0}
which gives me the following result using in the parameters
```
config.diarizer.vad.postprocessing_params.onset = 0.0
config.diarizer.vad.postprocessing_params.offset = 0.0
```
![image](https://user-images.githubusercontent.com/49493322/144496076-98390ac1-a366-4b28-a05e-bceb8761ab3c.png)

Using other values ​​for the same parameters I get the following result 
```
config.diarizer.vad.postprocessing_params.onset = 0.1
config.diarizer.vad.postprocessing_params.offset = 0.6
```
![image](https://user-images.githubusercontent.com/49493322/144496353-ceb85e51-abf7-4488-b034-b4caea75aa63.png)

Is there any reason he recommends onset 0.0 and offset 0.0 instead of
onset 0.1 and offset 0.6 or other better values?

I'm calling the script this way
```
!python /workspace/nemo/src/vad_tune_threshold.py \
--onset_range="0,1,0.2" --offset_range="0,1,0.2" \
--groundtruth_RTTM="/workspace/nemo/data_/PathRttm.txt" \
--vad_pred_method="frame" \
--vad_pred="/workspace/nemo/outputs/vad_outputs/"
```

Inside the PathRttm.txt has the path
/workspace/nemo/outputs/pred_rttms/Audio_Caio_Mais_Britadeira.rttm and in the vad_outputs folder there is the file: Audio_Caio_Mais_Britadeira.frame

**Comment by nithinraok** [comment] 2021-12-02 21:46
@fayejf

**Comment by fayejf** [comment] 2021-12-03 23:56
@CaioRochaGoes Hey sorry for late reply and thanks for your question. 

I think there is something wrong when you are using vad_tune_threshold.py because the **'FA (%)' and 'MISS (%)': are nan**. 

The script would recommend the parameters that give the smallest DER or FA or Miss as you choose.  

Do you mind share a test sample of your rttm that we can reproduce your observation?

**Comment by CaioRochaGoes** [comment] 2021-12-06 14:15
Here is the rttm file used:
[Audio_Caio_Mais_Britadeira.zip](https://github.com/NVIDIA/NeMo/files/7661260/Audio_Caio_Mais_Britadeira.zip)

**Comment by fayejf** [comment] 2021-12-07 23:13
@CaioRochaGoes The rttm looks fine. 
Is it possible to share `Audio_Caio_Mais_Britadeira` audio with us for debug? we would see if we can reproduce it on our end. The picture you shared above shows that VAD model generated acceptable prediction (green line). Not sure what causes `'FA (%)': nan, 'MISS (%)': nan`

**Comment by CaioRochaGoes** [comment] 2021-12-09 12:30
Hey, this is the audio I use for this test
[Audio_Caio_Mais_Britadeira.zip](https://github.com/NVIDIA/NeMo/files/7685048/Audio_Caio_Mais_Britadeira.zip)

**Comment by okuchaiev** [comment] 2022-04-05 23:43
Closing. @CaioRochaGoes please re-open if issue is still relevant.

**Closed by okuchaiev** 2022-04-05 23:43 UTC
Labels: feature request
