### ISSUE TITLE
[Question] : Docker image  nvcr.io/nvidia/nemo:v1.0.0b2 not found

### ISSUE THREAD

**Issue by harrypotter90** [NVIDIA/NeMo#1495] opened 2020-11-25 11:10 UTC
Docker image "v1.0.0b2 not found"

Error message:

docker pull nvcr.io/nvidia/nemo:v1.0.0b2
Error response from daemon: manifest for nvcr.io/nvidia/nemo:v1.0.0b2 not found: manifest unknown: manifest unknown

**Comment by harrypotter90** [comment] 2020-11-25 12:13
on the same machine, it works for "nvcr.io/nvidia/nemo:v1.0.0b1 "

**Comment by okuchaiev** [comment] 2020-11-30 18:07
closing as duplicate of https://github.com/NVIDIA/NeMo/issues/1498

**Closed by okuchaiev** 2020-11-30 18:07 UTC
Labels: question
