### ISSUE TITLE
Tensorboard step on resume training restarts from 0

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/NeMo#4541] opened 2022-07-12 16:05 UTC
**Describe the bug**

I have noticed that in previous nemo versions, e.g. 83444044327d8f0b697bbf0729bd96b7e16e3a56, Tensorboard showed consecutive steps when training was continued from the last checkpoint of an interrupted run; recent versions e.g. 77be76349901d0dd99ad6778509ef5c0663a65c3, as well as 1.10.0 do not; they always start from 0. Is this by intention or bug?

with 83444044327d8f0b697bbf0729bd96b7e16e3a56
<img width="365" alt="image" src="https://user-images.githubusercontent.com/4784070/178539639-a0e1cd2a-daf0-4460-96d1-20524bf4c969.png">

with 77be76349901d0dd99ad6778509ef5c0663a65c3
<img width="365" alt="image" src="https://user-images.githubusercontent.com/4784070/178539957-30a5d0cf-064d-4cbb-b850-e0b9d91aa4a9.png">

**Comment by titu1994** [comment] 2022-07-12 16:10
Wandb has changed it's logging, and it's somewhat broken right now such that it constantly resets to 0 when restoring (but internal PT value is correct global step similar to earlier plots). We're looking into soft patching this in Nemo until PTL / WandB fixes it. 

Fyi @MaximumEntropy

**Comment by MaximumEntropy** [comment] 2022-07-12 23:19
Hey! We just spoke to the PTL team earlier today and they mentioned that they had merged a fix to their main branch recently and should be part of their next release. If you have some time to test this, let us know how it goes!

**Comment by rohitgr7** [comment] 2022-07-13 16:31
hey @itzsimpl this is the correct version and should work. is it possible for you to share a reproducible script or maybe replicate the issue using [boring model](https://colab.research.google.com/github/Lightning-AI/lightning/blob/master/examples/pl_bug_report/bug_report_model.ipynb)??

thank you

**Comment by rohitgr7** [comment] 2022-07-13 17:40
qq: while restarting, did you use the checkpoint being saved with >=v1.6.5 or older?

**Comment by titu1994** [comment] 2022-07-14 02:46
Let's keep this open. Good to know newer PTL checkpoints will have the fix. The negative progressbar I've seen as well in my personal experiments on 1.6.4 PTL so I can verify it's an issue.

**Comment by rohitgr7** [comment] 2022-07-14 08:47
[a fix](https://github.com/Lightning-AI/lightning/pull/13645) is in progress that will enable you to use old checkpoints and resume the logging step.

Regarding the tqdm issue, can you open an issue on PL and also share a reproducible example?

**Comment by MaximumEntropy** [comment] 2022-07-14 20:01
Thanks for testing this @itzsimpl!

**Comment by MaximumEntropy** [comment] 2022-07-26 19:49
Closing since this seems to be fixed in PTL 1.6.5, please re-open if you're still seeing this or a separate one of negative step times.

**Closed by MaximumEntropy** 2022-07-26 19:49 UTC
Labels: bug
