### ISSUE TITLE
How to get the embedding from biomegatron?

### ISSUE THREAD

**Issue by sintaba** [NVIDIA/NeMo#2065] opened 2021-04-16 08:56 UTC
How to get the embedding from the BioMegatron checkpoint file?
Will there be any checkpoint converter for the BioMegatron in order to be loaded into Transformers?

**Comment by ericharper** [comment] 2021-04-20 05:23
Duplicate of https://github.com/NVIDIA/NeMo/discussions/2072

**Closed** 2021-04-20 05:22 UTC
Labels: question
