### ISSUE TITLE
Unable to load WaveGlow checkpoints or models: TypeError: Expected data to be int, Sequence or Mapping, but got NoneType

### ISSUE THREAD

**Issue by evelyn-f-king** [NVIDIA/NeMo#3494] opened 2022-01-22 23:45 UTC
**Describe the bug**

I can train WaveGlow models, but when I try to load checkpoints or `.nemo` files back, I am not able to.

**Steps/Code to reproduce bug**

Train, in a Google Colab GPU environment with or without Apex, a Waveglow 16khz model for one epoch. When attempting to load it back, either the checkpoint or the `.nemo` archive, I get the following error consistently:

```
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/supporters.py", line 589, in _nested_calc_num_data
    raise TypeError(f"Expected data to be int, Sequence or Mapping, but got {type(data).__name__}")
TypeError: Expected data to be int, Sequence or Mapping, but got NoneType
```

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

1. Train a new WaveGlow model for one epoch using the defaults, following the example in https://github.com/NVIDIA/NeMo/blob/main/examples/tts/waveglow.py. I have barely altered this, only adding a snippet to restore a model from a file.
2. Use `model = WaveGlowModel.restore_from(path_to_my_model)`. It will fail with the above error. Loading the checkpoint also fails with the same error.

**Expected behavior**

I expect to be able to load either checkpoints or `.nemo` files.
**Environment overview (please complete the following information)**

 - Environment location: colab
 - Method of NeMo install: [pip install or from source]. pip
 
**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version: Ubuntu 18.04 .5 LTS
- PyTorch version: 1.10.0+cu111
- Python version: Python 3.7.12

**Additional context**
I'm not sure if the fact that it's 16khz matters, but it's the only meaningful deviation  have from the example. Some online research suggests that this is because there's some mixed CPU/GPU training going on, but I wasn't able to find much more information than that, or how to fix it.

I will also note, that I expect a `.nemo` file for each checkpoint, and this does not seem to be the behavior - there seems to be just one `.nemo` file and many large `.ckpt` files, but this may be unrelated.

**Comment by evelyn-f-king** [comment] 2022-01-23 05:43
I just did more investigation to try and narrow this down even further, and switched back to LJSpeech from scratch. It doesn't matter if it's 22k or 16k- I can't load models.

**Comment by blisc** [comment] 2022-01-26 19:44
I cannot reproduce this on my end. Can you upload your checkpoint on google drive and/or create a colab notebook that replicates this error?

> I will also note, that I expect a .nemo file for each checkpoint, and this does not seem to be the behavior - there seems to be just one .nemo file and many large .ckpt files, but this may be unrelated.

This is the expected behaviour, you should expect 1 .nemo per run, and many .ckpt files. You can try to load the Lightning .ckpt files with `model = WaveGlowModel.load_from_checkpoint(path_to_ckpt)` and see if the lightning ckpt's also error out. If they don't you can always do  `model = WaveGlowModel.load_from_checkpoint(path_to_ckpt); model.save_to("new.nemo")` to get a .nemo file

**Comment by evelyn-f-king** [comment] 2022-02-01 04:21
I managed to reproduce this again. I trained a model for 100 epochs on one GPU, then killed the instance. On another GPU, it loaded fine, but on the third, it reproduced the error. I'm wondering if it has something to do with CUDA or maybe a misconfiguration? I ran the exact same notebook on all of them, but reloading the model only failed on the last machine. 

Then I tried training for two epochs on the last machine - the one that failed - and I could load it back.

I think the reason that my Colab restore failed is that there is something about the specific hardware configuration that causes a model trained on one GPU to be unable to be loaded on another. So, I can give you a notebook, but it's the same one I used when it worked as when it didn't. Is there anything I can do to mitigate/fix this? It's very expensive and time consuming to train a model and then I find out that I can't load it back.

**Comment by evelyn-f-king** [comment] 2022-02-01 04:29
I just discovered more, and maybe this is something I should be able to infer but I scoured the documentation and I could find no evidence of this - you seem to be unable to train on one GPU configuration and then resume on another, even if you modify it just slightly.

Here are some more specific repro steps:

1. Train a model for two epochs using the default WaveGlow config
2. Verify that you can load the model back.
3. Change the number of workers from 4 to 8.
4. The model will not load and you'll get the error. At least, I did.

**Comment by blisc** [comment] 2022-02-01 14:41
> 3. Change the number of workers from 4 to 8.

When you say workers here, do you mean GPUs? Going from a 4 GPU run to a 8 GPU run causes your checkpoint to error out?
Are you using difference GPU models?
Does the error still persist if you do `model.restore_from(model.nemo, map_location="cpu")` or `model.load_from_checkpoint(model.ckpt, map_location="cpu")`?

**Comment by evelyn-f-king** [comment] 2022-02-03 04:47
Going from a 4 GPU run to a 8 GPU run changes it, so does evidently changing `num_workers` in the `waveglow.yaml`
I'll give that a shot, thanks!

**Comment by ruisi-su** [comment] 2022-02-14 22:20
I encountered the same error `TypeError: Expected data to be int, Sequence or Mapping, but got NoneType` when calling `trainer.fit(model)` on the asr citrinet models with `from_pretrained(model_name, map_location=device)`. However, there is no error to train from scratch:
```python
model = nemo_asr.models.EncDecCTCModelBPE(
            cfg=params.model, trainer=trainer
        )
```
which successfully went into training.

Why is that the case? Since the asr ones don't have the option to specify `num_workers` at training time. What would be a solution here?

**Comment by evelyn-f-king** [comment] 2022-03-17 19:57
I hit this again. At some point, the training process spontaneously stops, and it doesn't seem to clean stuff up on the way out. The checkpoint is somehow corrupted and therefore useless.

I have saved an example checkpoint that has the issue, this time for a FastPitch model that I was finetuning. 1 GPU on this instance. I think the node count is a red herring, sorry for the confusion, was just trying to isolate what was different between my instances. I think the real difference was one had a transient network failure and one did not.

Converting it to a `.nemo` didn't make much of a difference, but it did reduce the file size for download, so here's a Drive link containing a broken model. https://drive.google.com/file/d/1REcYC8OPxF1V6dr9ITLo4O7NSCqteYhD/view?usp=sharing

**Comment by okuchaiev** [comment] 2022-04-05 23:54
Closing. @ruisi-su please open another one if you see that for ASR model.

**Closed by okuchaiev** 2022-04-05 23:54 UTC
Labels: bug
