### ISSUE TITLE
import FastPitchModel fails with unrelated error from prompth_encoder.py

### ISSUE THREAD

**Issue by bene-ges** [NVIDIA/NeMo#7238] opened 2023-08-15 19:21 UTC
**Describe the bug**

Running `tutorials/tts/FastPitch_Finetuning.ipynb` on Colab get error on `import FastPitchModel`

**Steps/Code to reproduce bug**
```
[/usr/local/lib/python3.10/dist-packages/nemo/collections/nlp/modules/common/prompt_encoder.py](https://localhost:8080/#) in TPMLP()
    138     def __init__(
    139         self,
--> 140         config: ModelParallelConfig,
    141         total_virtual_tokens: int,
    142         hidden_size: int,

NameError: name 'ModelParallelConfig' is not defined
```

**Comment by jeremiecoullon** [comment] 2023-08-16 10:30
Hello!

The same error happens if I run the [google colab for the NeMo forced aligner](https://colab.research.google.com/github/NVIDIA/NeMo/blob/main/tutorials/tools/NeMo_Forced_Aligner_Tutorial.ipynb).

**Steps to reproduce:**

Run the google colab until part 3 ("Run NFA"). The first code cell (`!python $NEMO_DIR_PATH/tools/nemo..etc..`) returns `NameError: name 'ModelParallelConfig' is not defined`

**Comment by rlangman** [comment] 2023-08-16 17:41
A lot of scripts are broken at the moment because of a commit involving Megatron `https://github.com/NVIDIA/NeMo/commit/4833347105b5ec8526ae182cd2e1011b091ea89d`

Until issues with this are resolved, I suggest using the commit before that one, like `https://github.com/NVIDIA/NeMo/commit/4833347105b5ec8526ae182cd2e1011b091ea89d`

For example if pip installing:

`python -m pip install git+https://github.com/NVIDIA/NeMo.git@f4afdf07ad742bdb2f45135f05d5d7dd8270eb51#egg=nemo_toolkit[all]`

**Comment by erastorgueva-nv** [comment] 2023-08-17 17:09
Hi @bene-ges and @jeremiecoullon, thanks for bringing this to our attention.
This issue has now been fixed in the https://github.com/NVIDIA/NeMo/pull/7254 PR.

**Closed by erastorgueva-nv** 2023-08-17 17:09 UTC
Labels: bug
